/* eslint-disable @typescript-eslint/no-empty-object-type */
// This file is auto-generated by Supabase

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      allowed_users: {
        Row: {
          id: string;
          email: string;
          role: string;
          is_club_member: boolean;
          invited_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          role?: string;
          is_club_member?: boolean;
          invited_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: string;
          is_club_member?: boolean;
          invited_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "allowed_users_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      profiles: {
        Row: {
          id: string;
          name: string | null;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      ingredients: {
        Row: {
          id: string;
          name: string;
          used_count: number;
          last_used_by: string | null;
          last_used_date: string | null;
          created_by: string | null;
          created_at: string;
          in_bank: boolean;
          color: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          used_count?: number;
          last_used_by?: string | null;
          last_used_date?: string | null;
          created_by?: string | null;
          created_at?: string;
          in_bank?: boolean;
          color?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          used_count?: number;
          last_used_by?: string | null;
          last_used_date?: string | null;
          created_by?: string | null;
          created_at?: string;
          in_bank?: boolean;
          color?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "ingredients_last_used_by_fkey";
            columns: ["last_used_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ingredients_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      recipes: {
        Row: {
          id: string;
          name: string;
          url: string | null;
          event_id: string | null;
          ingredient_id: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          url?: string | null;
          event_id?: string | null;
          ingredient_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          url?: string | null;
          event_id?: string | null;
          ingredient_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipes_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipes_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "scheduled_events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipes_ingredient_id_fkey";
            columns: ["ingredient_id"];
            isOneToOne: false;
            referencedRelation: "ingredients";
            referencedColumns: ["id"];
          }
        ];
      };
      recipe_notes: {
        Row: {
          id: string;
          recipe_id: string;
          user_id: string;
          notes: string | null;
          photos: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          user_id: string;
          notes?: string | null;
          photos?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          user_id?: string;
          notes?: string | null;
          photos?: string[] | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_notes_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipe_notes_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      recipe_ratings: {
        Row: {
          id: string;
          recipe_id: string;
          user_id: string;
          event_id: string;
          would_cook_again: boolean;
          overall_rating: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          user_id: string;
          event_id: string;
          would_cook_again: boolean;
          overall_rating: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          user_id?: string;
          event_id?: string;
          would_cook_again?: boolean;
          overall_rating?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_ratings_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipe_ratings_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipe_ratings_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "scheduled_events";
            referencedColumns: ["id"];
          }
        ];
      };
      recipe_content: {
        Row: {
          id: string;
          recipe_id: string;
          description: string | null;
          servings: string | null;
          prep_time: string | null;
          cook_time: string | null;
          total_time: string | null;
          instructions: Json | null;
          source_title: string | null;
          parsed_at: string | null;
          status: string;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          description?: string | null;
          servings?: string | null;
          prep_time?: string | null;
          cook_time?: string | null;
          total_time?: string | null;
          instructions?: Json | null;
          source_title?: string | null;
          parsed_at?: string | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          description?: string | null;
          servings?: string | null;
          prep_time?: string | null;
          cook_time?: string | null;
          total_time?: string | null;
          instructions?: Json | null;
          source_title?: string | null;
          parsed_at?: string | null;
          status?: string;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_content_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: true;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      recipe_ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          name: string;
          quantity: number | null;
          unit: string | null;
          category: string;
          raw_text: string | null;
          sort_order: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          name: string;
          quantity?: number | null;
          unit?: string | null;
          category?: string;
          raw_text?: string | null;
          sort_order?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          name?: string;
          quantity?: number | null;
          unit?: string | null;
          category?: string;
          raw_text?: string | null;
          sort_order?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_ingredients_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      user_pantry_items: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      event_grocery_cache: {
        Row: {
          id: string;
          event_id: string;
          items: Json;
          recipe_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          items: Json;
          recipe_ids: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          items?: Json;
          recipe_ids?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "event_grocery_cache_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: true;
            referencedRelation: "scheduled_events";
            referencedColumns: ["id"];
          }
        ];
      };
      scheduled_events: {
        Row: {
          id: string;
          ingredient_id: string | null;
          event_date: string;
          event_time: string | null;
          created_by: string | null;
          status: string;
          calendar_event_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          ingredient_id?: string | null;
          event_date: string;
          event_time?: string | null;
          created_by?: string | null;
          status?: string;
          calendar_event_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          ingredient_id?: string | null;
          event_date?: string;
          event_time?: string | null;
          created_by?: string | null;
          status?: string;
          calendar_event_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "scheduled_events_ingredient_id_fkey";
            columns: ["ingredient_id"];
            isOneToOne: false;
            referencedRelation: "ingredients";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "scheduled_events_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (Database["public"]["Tables"] & Database["public"]["Views"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (Database["public"]["Tables"] &
      Database["public"]["Views"])
  ? (Database["public"]["Tables"] &
      Database["public"]["Views"])[PublicTableNameOrOptions] extends {
      Row: infer R;
    }
    ? R
    : never
  : never;
